/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
//import java.awt.Color;
public class Mylogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mylogin.class.getName());

    /**
     * Creates new form Mylogin
     */
    public Mylogin() {
        initComponents();
        loadSavedCredentials();
    }
    private void loadSavedCredentials() {
    java.util.prefs.Preferences prefs = java.util.prefs.Preferences.userNodeForPackage(Mylogin.class);
    boolean remember = prefs.getBoolean("remember", false);
    
    if (remember) {
        String savedUser = prefs.get("username", "");
         String savedpass = prefs.get("password", "");
        jTextField1.setText(savedUser); // Put username back in text field
        jPasswordField1.setText(savedpass);
        jremember.setSelected(true);    // Keep checkbox checked
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bname = new javax.swing.JLabel();
        bpassword = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jremember = new javax.swing.JCheckBox();
        jPasswordField1 = new javax.swing.JPasswordField();
        jlogb = new javax.swing.JButton();
        jreset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        prgLoading = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Management System");

        bname.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        bname.setText("Username :");

        bpassword.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        bpassword.setText("Password : ");

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jremember.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jremember.setText("Remember Me");
        jremember.addActionListener(this::jrememberActionPerformed);

        jPasswordField1.setPreferredSize(new java.awt.Dimension(64, 22));

        jlogb.setBackground(new java.awt.Color(0, 102, 255));
        jlogb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlogb.setForeground(new java.awt.Color(255, 255, 255));
        jlogb.setText("Login");
        jlogb.setPreferredSize(new java.awt.Dimension(100, 30));
        jlogb.addActionListener(this::jlogbActionPerformed);

        jreset.setBackground(new java.awt.Color(0, 51, 255));
        jreset.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jreset.setForeground(new java.awt.Color(255, 255, 255));
        jreset.setText("Reset");
        jreset.setPreferredSize(new java.awt.Dimension(100, 30));
        jreset.addActionListener(this::jresetActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));

        prgLoading.setStringPainted(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(bname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(bpassword)
                        .addGap(25, 25, 25)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jlogb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220)
                        .addComponent(jreset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(prgLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jremember, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bname)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bpassword)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jremember)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlogb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jreset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(prgLoading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jlogbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogbActionPerformed
        // TODO add your handling code here:
String user = jTextField1.getText();
    String pass = new String(jPasswordField1.getPassword());

    // 1. Basic Validation
    if (user.isEmpty() || pass.isEmpty()) {
        jLabel3.setText("Fields cannot be empty!");
        jLabel3.setForeground(java.awt.Color.RED);
        return;
    }

    // 2. Prepare the Progress Bar
    prgLoading.setVisible(true);
    prgLoading.setValue(0);
    prgLoading.setStringPainted(true); // Shows the % text

    // 3. The Loading Timer (Animation + Database Call)
    javax.swing.Timer timer = new javax.swing.Timer(15, null); 
    timer.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            int current = prgLoading.getValue();
            if (current < 100) {
                prgLoading.setValue(current + 1); // Increase percentage
            } else {
                timer.stop(); // Stop animation at 100%
                
                // 4. Database logic runs AFTER the bar hits 100%
                try (Connection conn = DatabaseConnection.getConnection()) {
                    String sql = "SELECT * FROM users WHERE username=? AND password=?";
                    PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setString(1, user);
                    pst.setString(2, pass);

                    ResultSet rs = pst.executeQuery();
                    if (rs.next()) {
                        // Remember Me Logic
                        java.util.prefs.Preferences prefs = java.util.prefs.Preferences.userNodeForPackage(Mylogin.class);
                        if (jremember.isSelected()) {
                            prefs.put("username", user);
                            prefs.put("password", pass);
                            prefs.putBoolean("remember", true);
                        } else {
                            prefs.putBoolean("remember", false);
                        }

                        jLabel3.setText("Login Success");
                        jLabel3.setForeground(java.awt.Color.GREEN);

                        new MainPage().setVisible(true);
                        dispose(); // Close login window
                    } else {
                        jLabel3.setText("Login Failed");
                        jLabel3.setForeground(java.awt.Color.RED);
                        prgLoading.setVisible(false);
                    }
                } catch (SQLException ex) {
                    prgLoading.setVisible(false);
                    jLabel3.setText("Database Connection Error!");
                    ex.printStackTrace();
                }
            }
        }
    });
    timer.start();
    }//GEN-LAST:event_jlogbActionPerformed

    private void jresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jresetActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
    jPasswordField1.setText("");
    jremember.setSelected(false);
    jLabel3.setText(""); // Clears the Login Success/Failed message
    prgLoading.setVisible(false); // Hides the progress bar
    }//GEN-LAST:event_jresetActionPerformed

    private void jrememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrememberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrememberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Mylogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bname;
    private javax.swing.JLabel bpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jlogb;
    private javax.swing.JCheckBox jremember;
    private javax.swing.JButton jreset;
    private javax.swing.JProgressBar prgLoading;
    // End of variables declaration//GEN-END:variables
}
