/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
//import java.awt.Color;
public class Mylogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mylogin.class.getName());

    /**
     * Creates new form Mylogin
     */
    public Mylogin() {
        initComponents();
        loadSavedCredentials();
    }
    private void loadSavedCredentials() {
    java.util.prefs.Preferences prefs = java.util.prefs.Preferences.userNodeForPackage(Mylogin.class);
    boolean remember = prefs.getBoolean("remember", false);
    
    if (remember) {
        String savedUser = prefs.get("username", "");
         String savedpass = prefs.get("password", "");
        jTextField1.setText(savedUser); // Put username back in text field
        jPasswordField1.setText(savedpass);
        jremember.setSelected(true);    // Keep checkbox checked
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bname = new javax.swing.JLabel();
        bpassword = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jremember = new javax.swing.JCheckBox();
        jPasswordField1 = new javax.swing.JPasswordField();
        jlogb = new javax.swing.JButton();
        jreset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        prgLoading = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(380, 326));

        jPanel2.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(227, 242, 253));

        jLabel1.setBackground(new java.awt.Color(242, 242, 192));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 101, 192));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Management System");
        jLabel1.setPreferredSize(new java.awt.Dimension(380, 30));

        bname.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        bname.setText("Username :");
        bname.setPreferredSize(new java.awt.Dimension(100, 20));

        bpassword.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        bpassword.setText("Password : ");
        bpassword.setPreferredSize(new java.awt.Dimension(100, 20));

        jTextField1.setPreferredSize(new java.awt.Dimension(260, 28));
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jremember.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jremember.setText("Remember Me");
        jremember.setPreferredSize(new java.awt.Dimension(120, 24));
        jremember.addActionListener(this::jrememberActionPerformed);

        jPasswordField1.setPreferredSize(new java.awt.Dimension(260, 28));

        jlogb.setBackground(new java.awt.Color(0, 102, 255));
        jlogb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlogb.setForeground(new java.awt.Color(255, 255, 255));
        jlogb.setText("Login");
        jlogb.setAlignmentY(320.0F);
        jlogb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlogb.setPreferredSize(new java.awt.Dimension(100, 30));
        jlogb.addActionListener(this::jlogbActionPerformed);

        jreset.setBackground(new java.awt.Color(229, 57, 53));
        jreset.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jreset.setForeground(new java.awt.Color(255, 255, 255));
        jreset.setText("Reset");
        jreset.setAlignmentY(320.0F);
        jreset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jreset.setPreferredSize(new java.awt.Dimension(100, 30));
        jreset.addActionListener(this::jresetActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setPreferredSize(new java.awt.Dimension(320, 20));

        prgLoading.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        prgLoading.setForeground(new java.awt.Color(0, 0, 0));
        prgLoading.setPreferredSize(new java.awt.Dimension(300, 18));
        prgLoading.setStringPainted(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(bname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(bpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jremember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(prgLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jlogb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jreset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(bname, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(bpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jremember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlogb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jreset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(prgLoading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jlogbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogbActionPerformed
        // TODO add your handling code here:
String user = jTextField1.getText();
    String pass = new String(jPasswordField1.getPassword());

    // 1. Basic Validation
    if (user.isEmpty() || pass.isEmpty()) {
        jLabel3.setText("Fields cannot be empty!");
        jLabel3.setForeground(java.awt.Color.RED);
        return;
    }

    // 2. Prepare the Progress Bar
    prgLoading.setVisible(true);
    prgLoading.setValue(0);
    prgLoading.setStringPainted(true); // Shows the % text

    // 3. The Loading Timer (Animation + Database Call)
    javax.swing.Timer timer = new javax.swing.Timer(15, null); 
    timer.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            int current = prgLoading.getValue();
            if (current < 100) {
                prgLoading.setValue(current + 1); // Increase percentage
            } else {
                timer.stop(); // Stop animation at 100%
                
                // 4. Database logic runs AFTER the bar hits 100%
                try (Connection conn = DatabaseConnection.getConnection()) {
                    String sql = "SELECT * FROM users WHERE username=? AND password=?";
                    PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setString(1, user);
                    pst.setString(2, pass);

                    ResultSet rs = pst.executeQuery();
                    if (rs.next()) {
                        // Remember Me Logic
                        java.util.prefs.Preferences prefs = java.util.prefs.Preferences.userNodeForPackage(Mylogin.class);
                        if (jremember.isSelected()) {
                            prefs.put("username", user);
                            prefs.put("password", pass);
                            prefs.putBoolean("remember", true);
                        } else {
                            prefs.putBoolean("remember", false);
                        }

                        jLabel3.setText("Login Success");
                        jLabel3.setForeground(java.awt.Color.GREEN);

                        new MainPage().setVisible(true);
                        dispose(); // Close login window
                    } else {
                        jLabel3.setText("Login Failed");
                        jLabel3.setForeground(java.awt.Color.RED);
                        prgLoading.setVisible(false);
                    }
                } catch (SQLException ex) {
                    prgLoading.setVisible(false);
                    jLabel3.setText("Database Connection Error!");
                    ex.printStackTrace();
                }
            }
        }
    });
    timer.start();
    }//GEN-LAST:event_jlogbActionPerformed

    private void jresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jresetActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
    jPasswordField1.setText("");
    jremember.setSelected(false);
    jLabel3.setText(""); // Clears the Login Success/Failed message
    prgLoading.setVisible(false); // Hides the progress bar
    }//GEN-LAST:event_jresetActionPerformed

    private void jrememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrememberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrememberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Mylogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bname;
    private javax.swing.JLabel bpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jlogb;
    private javax.swing.JCheckBox jremember;
    private javax.swing.JButton jreset;
    private javax.swing.JProgressBar prgLoading;
    // End of variables declaration//GEN-END:variables
}
