/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BYUKUSENGE Ezira
 */
public class Registration extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registration.class.getName());

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFname = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        confirmpassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        loginhere = new javax.swing.JLabel();
        jLabel_Status = new javax.swing.JLabel();
        progressbar = new javax.swing.JProgressBar();
        jLabel8 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(238, 244, 255));

        jPanel1.setBackground(new java.awt.Color(238, 244, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(144, 180, 248)));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(21, 101, 192));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 118, 210));
        jLabel1.setText("CREATE ACCOUNT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 305, -1));

        jFname.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jFname.setForeground(new java.awt.Color(44, 62, 114));
        jFname.setText("First Name :");
        jFname.setPreferredSize(new java.awt.Dimension(130, 25));
        jPanel1.add(jFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 51, 80, -1));

        firstname.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        firstname.setForeground(new java.awt.Color(26, 39, 80));
        firstname.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(192, 221, 252), null));
        firstname.setPreferredSize(new java.awt.Dimension(250, 28));
        firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameFocusGained(evt);
            }
        });
        jPanel1.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 292, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(44, 62, 114));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Email  :  ");
        jLabel3.setPreferredSize(new java.awt.Dimension(130, 25));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        phoneNumber.setColumns(30);
        phoneNumber.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        phoneNumber.setForeground(new java.awt.Color(26, 39, 80));
        phoneNumber.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(192, 221, 252), null));
        phoneNumber.setPreferredSize(new java.awt.Dimension(255, 28));
        phoneNumber.addActionListener(this::phoneNumberActionPerformed);
        jPanel1.add(phoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 296, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(44, 62, 114));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Password :");
        jLabel4.setPreferredSize(new java.awt.Dimension(130, 25));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, -1));

        password.setColumns(20);
        password.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        password.setForeground(new java.awt.Color(26, 39, 80));
        password.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(192, 221, 252), null));
        password.setPreferredSize(new java.awt.Dimension(255, 28));
        password.setRequestFocusEnabled(false);
        password.addActionListener(this::passwordActionPerformed);
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 294, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(26, 39, 80));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Confirm Password :");
        jLabel5.setPreferredSize(new java.awt.Dimension(130, 25));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        confirmpassword.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        confirmpassword.setForeground(new java.awt.Color(26, 39, 80));
        confirmpassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(192, 221, 252), null));
        confirmpassword.setPreferredSize(new java.awt.Dimension(255, 28));
        confirmpassword.addActionListener(this::confirmpasswordActionPerformed);
        jPanel1.add(confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 246, -1));

        jButton1.setBackground(new java.awt.Color(25, 118, 210));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Register");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        loginhere.setBackground(new java.awt.Color(0, 204, 0));
        loginhere.setText("<html><u>Already have an account? Login here</u></html>");
        jPanel1.add(loginhere, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 200, -1));
        jPanel1.add(jLabel_Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        progressbar.setBackground(new java.awt.Color(21, 101, 192));
        progressbar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        progressbar.setForeground(new java.awt.Color(204, 255, 255));
        progressbar.setStringPainted(true);
        jPanel1.add(progressbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 10));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(44, 62, 114));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Last Name  :");
        jLabel8.setPreferredSize(new java.awt.Dimension(130, 25));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, -1));

        lastname.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lastname.setForeground(new java.awt.Color(26, 39, 80));
        lastname.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(192, 221, 252), null));
        lastname.setPreferredSize(new java.awt.Dimension(255, 28));
        lastname.addActionListener(this::lastnameActionPerformed);
        jPanel1.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 220, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(25, 118, 210));
        jLabel9.setText("PERSONAL INFO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 400, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(25, 118, 210));
        jLabel10.setText("SECURITY");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 460, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 0, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 470, 0));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 470, 0));

        jLabel12.setForeground(new java.awt.Color(44, 62, 114));
        jLabel12.setText("Phone :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        email.setColumns(30);
        email.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        email.setForeground(new java.awt.Color(26, 39, 80));
        email.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(192, 221, 252), null));
        email.setPreferredSize(new java.awt.Dimension(255, 28));
        email.addActionListener(this::emailActionPerformed);
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 296, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void confirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpasswordActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void phoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberActionPerformed

    private void firstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusGained
        // TODO add your handling code here:

        if (firstname.getText().equals("Enter your name")) {
            firstname.setText(""); // Clear the placeholder
            firstname.setForeground(java.awt.Color.BLACK); // Set text to solid black
        }
    }//GEN-LAST:event_firstnameFocusGained

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registration().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jFname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Status;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField lastname;
    private javax.swing.JLabel loginhere;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JProgressBar progressbar;
    // End of variables declaration//GEN-END:variables
}
